import TitleComponent from "src/components/Title";
import BodyComponent from "src/components/Body";
import ListItemComponent from "src/components/ListItem";
import InputComponent from "src/components/Input";
import TextAreaComponent from "src/components/TextArea";
import ButtonComponent from "src/components/Button";
import IconComponent from "src/components/Icon";
import TabItemComponent from "src/components/Tab/TabItem";
import ImageComponent from "src/components/Image";
import VerticalTabComponent from "src/components/Tab/VetricalTab";
import VerticalTabBodyOneComponent from "src/components/Tab/VerticalTabBody/BodyTypeOne";
import VerticalTabBodyTwoComponent from "src/components/Tab/VerticalTabBody/BodyTypeTwo";

export const Title = TitleComponent;
export const Body = BodyComponent;
export const ListItem = ListItemComponent;
export const Input = InputComponent;
export const TextArea = TextAreaComponent;
export const Button = ButtonComponent;
export const Icon = IconComponent;
export const TabItem = TabItemComponent;
export const Image = ImageComponent;
export const VerticalTab = VerticalTabComponent;
export const VerticalTabBodyOne = VerticalTabBodyOneComponent;
export const VerticalTabBodyTwo = VerticalTabBodyTwoComponent;
